package org.apache.torque.tutorial.om;

/**
 * Author Table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Apr 19 23:41:41 AZT 2022]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class AuthorPeer
    extends org.apache.torque.tutorial.om.BaseAuthorPeer
{

}
