package org.apache.torque.tutorial.om;

/**
 * Book Table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Apr 19 23:41:41 AZT 2022]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class BookPeerImpl
    extends org.apache.torque.tutorial.om.BaseBookPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1650397301301L;



}
