package org.apache.torque.tutorial.om;


/**
 * Maps ResultSet rows into Book objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Apr 19 23:41:41 AZT 2022]
 *
 */
public class BookRecordMapper extends BaseBookRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1650397301565L;



}
