package org.apache.torque.tutorial.om;


/**
 * Maps ResultSet rows into Publisher objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Apr 19 23:41:41 AZT 2022]
 *
 */
public class PublisherRecordMapper extends BasePublisherRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1650397301561L;



}
