package org.apache.torque.tutorial.om;


/**
 * Publisher Table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Apr 19 23:41:41 AZT 2022]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class Publisher
    extends org.apache.torque.tutorial.om.BasePublisher
{
    /** Serial version */
    private static final long serialVersionUID = 1650397301040L;



}
